// Generated by the Prototype & Chill Name Matcher — May 15, 2026
// Re-export this file from the matcher tool when assignments change, then push to GitHub.
window.ASSIGNMENTS = [
  {
    "name": "Alice",
    "brief": "I can never find the latest version of a design file — they multiply and I don't know which one is real",
    "email": "",
    "timezone": "India",
    "assignedTo": "Dana",
    "assignedBrief": "Every meeting has a notes doc that no one ever opens again, including me",
    "theme": "Gordon Ramsay's Kitchen"
  },
  {
    "name": "Bob",
    "brief": "I spend 20 minutes every Monday morning figuring out what I was doing Friday afternoon",
    "email": "",
    "timezone": "US",
    "assignedTo": "Frank",
    "assignedBrief": "I copy the same boilerplate into every new project and it takes forever and I always forget something",
    "theme": "Game Show"
  },
  {
    "name": "Charlie",
    "brief": "Feedback comes in from Slack, email, Figma comments, and a sticky note on my monitor — I lose half of it",
    "email": "",
    "timezone": "Europe",
    "assignedTo": "Eve",
    "assignedBrief": "I have 12 Figma pages called \"New Page\" and genuinely no idea what's in any of them",
    "theme": "Confetti & Party"
  },
  {
    "name": "Dana",
    "brief": "Every meeting has a notes doc that no one ever opens again, including me",
    "email": "",
    "timezone": "India",
    "assignedTo": "Hal",
    "assignedBrief": "My laptop always picks the worst possible moment to do a software update",
    "theme": "The Oracle"
  },
  {
    "name": "Eve",
    "brief": "I have 12 Figma pages called \"New Page\" and genuinely no idea what's in any of them",
    "email": "",
    "timezone": "Europe",
    "assignedTo": "Charlie",
    "assignedBrief": "Feedback comes in from Slack, email, Figma comments, and a sticky note on my monitor — I lose half of it",
    "theme": "Luxury Fashion Brand"
  },
  {
    "name": "Frank",
    "brief": "I copy the same boilerplate into every new project and it takes forever and I always forget something",
    "email": "",
    "timezone": "US",
    "assignedTo": "Bob",
    "assignedBrief": "I spend 20 minutes every Monday morning figuring out what I was doing Friday afternoon",
    "theme": "Mobile-First (Literally)"
  },
  {
    "name": "Grace",
    "brief": "I can never remember our brand hex codes without opening Figma and digging through the style panel",
    "email": "",
    "timezone": "India",
    "assignedTo": "Alice",
    "assignedBrief": "I can never find the latest version of a design file — they multiply and I don't know which one is real",
    "theme": "Horror Game"
  },
  {
    "name": "Hal",
    "brief": "My laptop always picks the worst possible moment to do a software update",
    "email": "",
    "timezone": "US",
    "assignedTo": "Grace",
    "assignedBrief": "I can never remember our brand hex codes without opening Figma and digging through the style panel",
    "theme": "Airport Departures Board"
  }
];
window.THEME_DATA = [
  {
    "num": "01",
    "name": "The \"Secret Agent\"",
    "desc": "All text is written in a code or top secret font. Classified stamp on every page.",
    "constraint": "The app self-destructs (auto-refreshes) after 5 minutes of inactivity."
  },
  {
    "num": "02",
    "name": "The \"Drunk\" UI",
    "desc": "Everything is tilted 1–3 degrees. Buttons wobble when you try to click them.",
    "constraint": "The cursor occasionally drifts slightly in the wrong direction."
  },
  {
    "num": "03",
    "name": "Comic Sans Professional",
    "desc": "The entire tool is built using only Comic Sans and retro gradients. No exceptions.",
    "constraint": "Every button must use WordArt-style text with at least 3 colors."
  },
  {
    "num": "04",
    "name": "Maximalist / Scrappy",
    "desc": "No white space allowed. Every pixel must be doing something.",
    "constraint": "At least one element must be blinking at all times."
  },
  {
    "num": "05",
    "name": "Confetti & Party",
    "desc": "Every successful action triggers a confetti explosion or celebratory sound effect.",
    "constraint": "There's a hidden \"ultra party mode\" button somewhere on the page. Finding it makes everything 10x more chaotic."
  },
  {
    "num": "06",
    "name": "Mobile-First (Literally)",
    "desc": "The app runs in a browser but is permanently stuck in an iPhone frame in the center of the screen.",
    "constraint": "A fake battery indicator in the corner is always at 4%."
  },
  {
    "num": "07",
    "name": "The \"Clippy\" Assistant",
    "desc": "A small, unhelpful character lives in the corner and interrupts the user with bad tips.",
    "constraint": "The character gets visibly offended if ignored for more than 30 seconds."
  },
  {
    "num": "08",
    "name": "Sci-Fi Terminal",
    "desc": "Looks like a computer interface from 200 years in the future. Scanning animations, hexagons, green glow.",
    "constraint": "Every error must read: \"SYSTEM FAILURE — PROBABILITY OF SURVIVAL: 12%.\""
  },
  {
    "num": "09",
    "name": "Tamagotchi",
    "desc": "The app looks and functions like a Tamagotchi. Multiple sound effects. Pixel art mandatory.",
    "constraint": "The pet visibly deteriorates if you don't interact with the UI every 2 minutes."
  },
  {
    "num": "10",
    "name": "Post-Apocalyptic Terminal",
    "desc": "Delivered through a dramatic command-line interface. Everything is urgent. The world has ended.",
    "constraint": "Every action has a 10% chance of returning an ominous message about \"what happened to the others.\""
  },
  {
    "num": "11",
    "name": "Paranormal",
    "desc": "Supernatural aesthetic. Eerie, ghostly, deeply unsettling. But you can only use one color.",
    "constraint": "Once per session, some text on the page rearranges itself on its own."
  },
  {
    "num": "12",
    "name": "Windows 95",
    "desc": "Looks exactly like a desktop app from 1995. Bevelled buttons, grey everything, system fonts only.",
    "constraint": "Must include a fake loading bar that gets to 97% and then pauses for 3 full seconds."
  },
  {
    "num": "13",
    "name": "The Infomercial",
    "desc": "Everything looks and sounds like a late-night shopping channel. Prices everywhere. \"ACT NOW\" buttons. Limited time offers on every feature.",
    "constraint": "A ticker tape runs along the bottom the entire time promoting the app's own features."
  },
  {
    "num": "14",
    "name": "Nature Documentary",
    "desc": "Every interaction is captioned as if observing a rare species in the wild. Loading states are long, dramatic pauses.",
    "constraint": "At least one action must trigger ambient nature sounds and a 4-second caption before anything happens."
  },
  {
    "num": "15",
    "name": "The Oracle",
    "desc": "Everything is phrased as mystical prophecy. Buttons say \"Seek the truth\" instead of \"Submit.\" The UI knows things it shouldn't.",
    "constraint": "Error messages are delivered as riddles. The user must figure out what went wrong."
  },
  {
    "num": "16",
    "name": "Gordon Ramsay's Kitchen",
    "desc": "The UI is a cooking competition. Every action is a step in a recipe. Buttons say \"Prep,\" \"Cook,\" \"Plate.\" Errors are culinary disasters.",
    "constraint": "Every mistake triggers an ALL CAPS message. \"THIS IS RAW. ABSOLUTELY RAW.\""
  },
  {
    "num": "17",
    "name": "Breaking News",
    "desc": "Full 24-hour news channel aesthetic. Lower thirds, a BREAKING banner, ticker tape running constantly, urgent music energy.",
    "constraint": "Every action you take is reported as a breaking news story with its own dramatic chyron."
  },
  {
    "num": "18",
    "name": "Airport Departures Board",
    "desc": "Everything flips like a split-flap arrivals board. Loading states are just the board slowly flipping through letters.",
    "constraint": "At some point, for no reason, everything on the board changes to CANCELLED."
  },
  {
    "num": "19",
    "name": "IKEA Manual",
    "desc": "No text allowed anywhere. All instructions must be communicated through numbered diagrams only.",
    "constraint": "One diagram must be subtly, quietly wrong."
  },
  {
    "num": "20",
    "name": "Wikipedia Spiral",
    "desc": "Everything is a blue hyperlink. Every element is clickable and leads somewhere else. Nothing is a dead end.",
    "constraint": "Every path eventually leads to the same page."
  },
  {
    "num": "21",
    "name": "Grocery Store Flyer",
    "desc": "Prices in big red circles. SALE banners everywhere. Everything is on special this week only.",
    "constraint": "There must be a \"Manager's Special\" section that makes no sense for the app."
  },
  {
    "num": "22",
    "name": "Children's Learning App",
    "desc": "Big colorful buttons, simple words, extremely encouraging. The app treats you like you are four years old.",
    "constraint": "Every completed action plays a sound and says \"GREAT JOB!\" There is no mute button."
  },
  {
    "num": "23",
    "name": "Luxury Fashion Brand",
    "desc": "Sparse. High-contrast. One font. Extremely serious. Everything costs $4,000 and the UI knows it.",
    "constraint": "The app loads for exactly 3 seconds every time — not because it needs to, but for the drama."
  },
  {
    "num": "24",
    "name": "Medieval Illuminated Manuscript",
    "desc": "Old English script, decorative borders, illustrated drop capitals. Deeply formal. Extremely old.",
    "constraint": "All error messages must be written as royal proclamations."
  },
  {
    "num": "25",
    "name": "Tech Startup Landing Page",
    "desc": "\"AI-powered.\" \"Disrupting the industry.\" \"The future of [thing].\" Every feature is revolutionary.",
    "constraint": "Must include a fake testimonial from a suspiciously vague source like \"— J.T., CEO.\""
  },
  {
    "num": "26",
    "name": "Horror Game",
    "desc": "Dark, ominous, every click feels like a mistake. UI elements appear slowly. Something is wrong but you can't tell what.",
    "constraint": "At least one interaction must have a jump scare."
  },
  {
    "num": "27",
    "name": "Retro Arcade",
    "desc": "Pixel art, 8-bit everything, score counter in the corner, insert coin energy.",
    "constraint": "Every action costs credits. When you run out, a GAME OVER screen appears."
  },
  {
    "num": "28",
    "name": "Weather Forecast",
    "desc": "Everything is a weather metaphor. Loading is \"partly cloudy.\" Errors are \"severe weather warnings.\" The forecast is always bad.",
    "constraint": "The outlook for completing your task must always read \"turbulent, with a 30% chance of success.\""
  },
  {
    "num": "29",
    "name": "Dating App",
    "desc": "Every screen is a swipe decision. Even error messages must be swiped away.",
    "constraint": "The app periodically asks you to rate your experience with the UI on a scale of \"not my type\" to \"it's a match.\""
  },
  {
    "num": "30",
    "name": "Game Show",
    "desc": "Everything is a game show. Multiple choice everywhere. Wrong answers trigger a dramatic sound. There is always a countdown timer.",
    "constraint": "At the end, a wheel spins to determine if your submission \"counts.\""
  },
  {
    "num": "31",
    "name": "Telenovela",
    "desc": "Every action has enormous emotional stakes. Every button press is a betrayal. Every error is a revelation.",
    "constraint": "At least one dramatic portrait must appear on screen at a pivotal moment."
  },
  {
    "num": "32",
    "name": "NASA Mission Control",
    "desc": "You are the flight director. Everything is a mission. Checklists, status boards, countdowns.",
    "constraint": "Any error triggers a \"we have a problem\" alert and the entire room panics."
  },
  {
    "num": "33",
    "name": "Everything is Rated",
    "desc": "Every element in the UI has a star rating. The buttons. The labels. The error messages. The font.",
    "constraint": "There is a 1-star review of the app itself pinned to the top of every page."
  },
  {
    "num": "34",
    "name": "Personal Trainer",
    "desc": "The app is your coach. Motivational, intense, slightly aggressive. Every action is a rep.",
    "constraint": "Pause for more than 30 seconds and it starts a timer and plays pump-up music."
  },
  {
    "num": "35",
    "name": "Cruise Ship Activities Board",
    "desc": "Cheerful, pastel, laminated energy. Everything is an \"activity\" with a time and deck number.",
    "constraint": "Every page has an ad for the buffet. There is no reason for this."
  },
  {
    "num": "36",
    "name": "Real Estate Listing",
    "desc": "All copy is written in estate agent language. \"Cosy\" means small. \"Opportunity to improve\" means broken.",
    "constraint": "Every screen has a photo slider with 47 images of the same room from slightly different angles."
  },
  {
    "num": "37",
    "name": "DJ Set",
    "desc": "Everything pulses to a beat. BPM counter in the corner. A drop is always incoming.",
    "constraint": "At exactly one moment, the drop hits and the entire UI goes full rave for 3 seconds."
  },
  {
    "num": "38",
    "name": "Japanese Game Show",
    "desc": "Chaotic, colorful, extremely high stakes, rules are unclear, everyone is very enthusiastic.",
    "constraint": "A countdown timer appears at random and no one explains why."
  },
  {
    "num": "39",
    "name": "Medical Chart",
    "desc": "Clinical. Forms everywhere. Nothing is intuitive and that is by design.",
    "constraint": "Every action requires a signature. There is no visible signature field. You must find it."
  },
  {
    "num": "40",
    "name": "PowerPoint You Cannot Escape",
    "desc": "The entire app is a slideshow. You may only use Previous and Next to navigate. There is no menu.",
    "constraint": "At some point a slide transition takes 8 seconds and cannot be skipped."
  }
];